asset: lagoon-cli-$STABLE_VERSION-darwin-amd64.tar.gz
tap: amazeeio/homebrew-lagoon-cli/lagoon.rb
template: >
  class Lagoon < Formula
    desc     "Command line tool for interacting with a Lagoon API"
    homepage "https://github.com/amazeeio/lagoon-cli"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"

    bottle :unneeded

    def install
      prefix.install "lagoon"
    end
  end