version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/amazeeio/lagoon-cli
    steps:
      - checkout
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: run tests
          command: make test
  deploy:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/amazeeio/lagoon-cli
    steps:
      - checkout
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: compile
          command: |
            make VERSION=${CIRCLE_BRANCH} build-linux
            make VERSION=${CIRCLE_BRANCH} build-darwin
      - run:
          name: "Publish Release on GitHub"
          command: |
            GO111MODULE=auto go get github.com/tcnksm/ghr
            VERSION=${CIRCLE_BRANCH}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./builds/lagoon-cli-*
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
