version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/amazeeio/lagoon-cli
    steps:
      - checkout
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: run tests
          command: make test
  deploy:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/amazeeio/lagoon-cli
    steps:
      - checkout
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: cross compile
          command: |
            make build-linux
            make build-darwin
      - store_artifacts:
          path: builds
          name: Artifact storage
    # publish:
    #   docker:
    #     - image: cibuilds/github:0.10
    #   steps:
    #     - attach_workspace:
    #         at: ./builds
    #     - run:
    #         name: "Publish Release on GitHub"
    #         command: |
    #           VERSION=$(my-binary --version)
    #           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} \
    #             -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} \
    #             -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      # - publish:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^\d+\.\d+\.\d+$/
