version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/amazeeio/lagoon-cli
    steps:
      - checkout
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: run tests
          command: make test
  deploy:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/amazeeio/lagoon-cli
    steps:
      - checkout
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: cross compile
          command: |
            make build-linux
            make build-darwin
      - store_artifacts:
          path: builds
          name: Artifact storage
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
